ARG ARCHTAG
FROM openwebrxplus-soapysdr-base:$ARCHTAG

COPY docker/scripts/install-dependencies-limesdr.sh /
RUN /install-dependencies-limesdr.sh &&\
    rm /install-dependencies-limesdr.sh

COPY . /opt/openwebrx
